version: '2'

services:

  api:
    extends:
      file: base-compose.yml
      service: api
    command: bundle exec rails s Puma -p 8080 -b '0.0.0.0' -e production
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: haha123sosecret
    networks:
      - frontend
      - backend

  worker:
    extends:
      file: base-compose.yml
      service: worker
    environment:
      RAILS_ENV: production
    networks:
      - backend

  redis:
    extends:
      file: base-compose.yml
      service: redis
    networks:
      - backend

  postgres:
    extends:
      file: base-compose.yml
      service: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    networks:
      - backend

volumes:
  pg_data: {}

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
